name: gardenguru
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^10.2.6
  firebase_core: ^2.16.0
  google_fonts: ^5.1.0
  provider: ^6.0.5
  auto_route: ^7.8.3
  counter_button: ^1.0.1
  image_picker: ^1.0.4
  socket_io_client: ^2.0.3+1 
  dotted_border: ^2.0.0+3
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/plants/
    - assets/category/
    - assets/shopping/
    - assets/other_material/
    - assets/disease/
    

  